version: "3"
services:
  sqldb:
    image: 'mcr.microsoft.com/mssql/server'
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
  hivemq:
    image: hivemq/hivemq4
    ports:
      - 1883:1883
      - 9001:9001
      - 8080:8080
  redis:
    container_name: IOT-redis
    image: redis:6.2-alpine
    hostname: redis
    ports:
      - '6379:6379'
volumes:
  db_data: ~
